name: deploy on push
on: ["prod"]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_PORT }}
          port: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
